"""Fix FKs to users instead of employees

Revision ID: 4109a8b1d198
Revises: fef5c9d0dc68
Create Date: 2026-07-12 15:25:49.870240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4109a8b1d198'
down_revision: Union[str, Sequence[str], None] = 'fef5c9d0dc68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('carbon_transactions', 'organization_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('carbon_transactions_employee_id_fkey'), 'carbon_transactions', type_='foreignkey')
    op.create_foreign_key(None, 'carbon_transactions', 'users', ['employee_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'carbon_transactions', type_='foreignkey')
    op.create_foreign_key(op.f('carbon_transactions_employee_id_fkey'), 'carbon_transactions', 'employees', ['employee_id'], ['id'], ondelete='CASCADE')
    op.alter_column('carbon_transactions', 'organization_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
