"""Make organization_id nullable everywhere

Revision ID: 89b2388576d6
Revises: d554413569f7
Create Date: 2026-07-12 15:38:21.602600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89b2388576d6'
down_revision: Union[str, Sequence[str], None] = 'd554413569f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audits', 'organization_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('badges', 'organization_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('challenges', 'organization_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('csr_activities', 'organization_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('departments', 'organization_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('policies', 'organization_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('rewards', 'organization_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rewards', 'organization_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('policies', 'organization_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('departments', 'organization_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('csr_activities', 'organization_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('challenges', 'organization_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('badges', 'organization_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('audits', 'organization_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
