"""Fix FKs to users in gamification and governance

Revision ID: d554413569f7
Revises: 4109a8b1d198
Create Date: 2026-07-12 15:34:12.541073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd554413569f7'
down_revision: Union[str, Sequence[str], None] = '4109a8b1d198'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('employee_badges_employee_id_fkey'), 'employee_badges', type_='foreignkey')
    op.create_foreign_key(None, 'employee_badges', 'users', ['employee_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('policy_acknowledgements_employee_id_fkey'), 'policy_acknowledgements', type_='foreignkey')
    op.create_foreign_key(None, 'policy_acknowledgements', 'users', ['employee_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('xp_transactions_employee_id_fkey'), 'xp_transactions', type_='foreignkey')
    op.create_foreign_key(None, 'xp_transactions', 'users', ['employee_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'xp_transactions', type_='foreignkey')
    op.create_foreign_key(op.f('xp_transactions_employee_id_fkey'), 'xp_transactions', 'employees', ['employee_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'policy_acknowledgements', type_='foreignkey')
    op.create_foreign_key(op.f('policy_acknowledgements_employee_id_fkey'), 'policy_acknowledgements', 'employees', ['employee_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'employee_badges', type_='foreignkey')
    op.create_foreign_key(op.f('employee_badges_employee_id_fkey'), 'employee_badges', 'employees', ['employee_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
