"""Update participation FK

Revision ID: fef5c9d0dc68
Revises: e195ecc17588
Create Date: 2026-07-12 14:47:25.345721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fef5c9d0dc68'
down_revision: Union[str, Sequence[str], None] = 'e195ecc17588'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('employee_participations_employee_id_fkey'), 'employee_participations', type_='foreignkey')
    op.create_foreign_key(None, 'employee_participations', 'users', ['employee_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employee_participations', type_='foreignkey')
    op.create_foreign_key(op.f('employee_participations_employee_id_fkey'), 'employee_participations', 'employees', ['employee_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
